version: '3'

services:
    keycloak:
        image: docker.io/bitnami/keycloak:20
        restart: always
        ports:
            - '8443:8443'
        environment:
            KEYCLOAK_CREATE_ADMIN_USER: ${KEYCLOAK_CREATE_ADMIN_USER}
            KEYCLOAK_ADMIN_USER: ${KEYCLOAK_ADMIN_USER}
            KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
            KEYCLOAK_MANAGEMENT_USER: ${KEYCLOAK_MANAGEMENT_USER}
            KEYCLOAK_MANAGEMENT_PASSWORD: ${KEYCLOAK_MANAGEMENT_PASSWORD}

            KEYCLOAK_ENABLE_HTTPS: 'true'
            KEYCLOAK_HTTPS_USE_PEM: 'true'
            KEYCLOAK_HTTPS_CERTIFICATE_FILE: ${KEYCLOAK_HTTPS_CERTIFICATE_FILE:-/opt/bitnami/keycloak/certs/tls.crt}
            KEYCLOAK_HTTPS_CERTIFICATE_KEY_FILE: ${KEYCLOAK_HTTPS_CERTIFICATE_KEY_FILE:-/opt/bitnami/keycloak/certs/tls.key}

            KEYCLOAK_DATABASE_HOST: ${KEYCLOAK_DATABASE_HOST:-postgresql}
            KEYCLOAK_DATABASE_PORT: ${KEYCLOAK_DATABASE_PORT:-5432}
            KEYCLOAK_DATABASE_NAME: ${KEYCLOAK_DATABASE_NAME:-keycloak}
            KEYCLOAK_DATABASE_USER: ${KEYCLOAK_DATABASE_USER:-keycloak}
            KEYCLOAK_DATABASE_PASSWORD: ${POSTGRESQL_PASSWORD}
        volumes:
            - ./certs/keycloak:/opt/bitnami/keycloak/certs
        depends_on:
            postgresql:
                condition: service_healthy
        healthcheck:
            test: curl --fail --insecure https://localhost:8443/
            interval: 3s
            timeout: 5s
            retries: 20
            start_period: 5s

    postgresql:
        image: docker.io/bitnami/postgresql:15
        restart: always
        environment:
            POSTGRESQL_USERNAME: keycloak
            POSTGRESQL_PASSWORD: ${POSTGRESQL_PASSWORD}
            POSTGRESQL_DATABASE: keycloak
        volumes:
            - postgresql_data:/bitnami/postgresql
        healthcheck:
            test: ['CMD-SHELL', 'pg_isready -U keycloak']
            interval: 5s
            timeout: 5s
            retries: 5

    opensearch-node1:
        image: opensearchproject/opensearch:2.4.1
        restart: always
        container_name: opensearch-node1
        environment:
            - node.name=opensearch-node1
            - 'OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m' # Set min and max JVM heap sizes to at least 50% of system RAM
            - 'DISABLE_INSTALL_DEMO_CONFIG=true' # Prevents execution of bundled demo script which installs demo certificates and security configurations to OpenSearch
        ulimits:
            memlock:
                soft: -1 # Set memlock to unlimited (no soft or hard limit)
                hard: -1
            nofile:
                soft: 65536 # Maximum number of open files for the opensearch user - set to at least 65536
                hard: 65536
        volumes:
            - opensearch-data1:/usr/share/opensearch/data
            - ./config/opensearch.yml:/usr/share/opensearch/config/opensearch.yml
            - ./config/opensearch-security.yml:/usr/share/opensearch/config/opensearch-security/config.yml
            - ./certs:/usr/share/opensearch/config/certificates:ro
        ports:
            - 9200:9200 # REST API
            - 9600:9600 # Performance Analyzer
        depends_on:
            keycloak:
                condition: service_healthy
        healthcheck:
            test: curl -IL --silent --insecure https://localhost:9200 | grep HTTP | grep 401
            interval: 10s
            timeout: 10s
            retries: 15
            start_period: 5s

    opensearch-node2:
        image: opensearchproject/opensearch:2.4.1
        restart: always
        container_name: opensearch-node2
        environment:
            - node.name=opensearch-node2
            - 'OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m'
            - 'DISABLE_INSTALL_DEMO_CONFIG=true'
        ulimits:
            memlock:
                soft: -1
                hard: -1
            nofile:
                soft: 65536
                hard: 65536
        volumes:
            - opensearch-data2:/usr/share/opensearch/data
            - ./config/opensearch.yml:/usr/share/opensearch/config/opensearch.yml
            - ./config/opensearch-security.yml:/usr/share/opensearch/config/opensearch-security/config.yml
            - ./certs:/usr/share/opensearch/config/certificates:ro
        depends_on:
            keycloak:
                condition: service_healthy
        healthcheck:
            test: curl -IL --silent --insecure https://localhost:9200 | grep HTTP | grep 401
            interval: 10s
            timeout: 10s
            retries: 15
            start_period: 5s

    opensearch-node3:
        image: opensearchproject/opensearch:2.4.1
        restart: always
        container_name: opensearch-node3
        environment:
            - node.name=opensearch-node3
            - 'OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m'
            - 'DISABLE_INSTALL_DEMO_CONFIG=true'
        ulimits:
            memlock:
                soft: -1
                hard: -1
            nofile:
                soft: 65536
                hard: 65536
        volumes:
            - opensearch-data3:/usr/share/opensearch/data
            - ./config/opensearch.yml:/usr/share/opensearch/config/opensearch.yml
            - ./config/opensearch-security.yml:/usr/share/opensearch/config/opensearch-security/config.yml
            - ./certs:/usr/share/opensearch/config/certificates:ro
        depends_on:
            keycloak:
                condition: service_healthy
        healthcheck:
            test: curl -IL --silent --insecure https://localhost:9200 | grep HTTP | grep 401
            interval: 10s
            timeout: 10s
            retries: 15
            start_period: 5s

    opensearch-dashboards:
        image: opensearchproject/opensearch-dashboards:2.4.1
        restart: always
        container_name: opensearch-dashboards
        ports:
            - 5601:5601
        volumes:
            - ./config/opensearch-dashboards.yml:/usr/share/opensearch-dashboards/config/opensearch_dashboards.yml
            - ./certs:/usr/share/opensearch-dashboards/config/certificates:ro
        depends_on:
            keycloak:
                condition: service_healthy
            opensearch-node1:
                condition: service_healthy
        healthcheck:
            test: sh -c "curl --fail --insecure https://localhost:5601/auth/openid/login || kill 1"
            timeout: 10s
            retries: 1
            start_period: 30s

volumes:
    opensearch-data1:
    opensearch-data2:
    opensearch-data3:
    postgresql_data:
        driver: local
